Repository ajounice/MomenTrip_BE, pull requests merged in 2022-12, with the labels that each got.

#43 Refactor/user response
  src/modules/users/UserController.ts
  src/modules/users/dto/CreateUserInfoRequest.ts
  src/modules/users/dto/UpdateUserInfoRequest.ts
  src/modules/users/dto/index.ts
  src/modules/users/dto/response/FollowResponse.ts
  src/modules/users/dto/response/IsFollowingResponse.ts
  src/modules/users/dto/response/UserInfoResponse.ts
  src/modules/users/dto/response/UserListResponse.ts
  src/modules/users/dto/response/UserProfileImageResponse.ts
  src/modules/users/dto/response/index.ts
  src/modules/users/services/UserProfileService.ts
Labels: refactor

#51 refactor: Fix wishlistItem dto, wishlistItem Service
  src/modules/wishlists/WishlistController.ts
  src/modules/wishlists/dtos/response/WishlisItemResponse.ts
  src/modules/wishlists/services/WishlistFolderService.ts
  src/modules/wishlists/services/WishlistItemService.ts
Labels: refactor

#49 비밀번호 변경 API 작업
  src/modules/users/UserController.ts
  src/modules/users/dto/request/CreateUserInfoRequest.ts
  src/modules/users/dto/request/UpdatePasswordRequest.ts
  src/modules/users/dto/request/UpdateUserInfoRequest.ts
  src/modules/users/dto/request/index.ts
  src/modules/users/dto/response/UpdatePasswordResponse.ts
  src/modules/users/dto/response/index.ts
  src/modules/users/services/UserProfileService.ts
  src/modules/users/services/UserService.ts
Labels: feature

#55 메시지 큐를 적용한 프로젝트 구조 및 코드 로직 개선
  .env.example
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
  src/common/utils/FileStorage.ts
  src/common/utils/VideoConsumer.ts
  src/common/utils/VideoConverter.ts
  src/common/utils/VideoProducer.ts
  src/common/utils/index.ts
  src/modules/common/CommonModule.ts
  src/modules/common/CommonService.ts
  src/modules/forms/services/FormService.ts
Labels: enhancement, refactor, fix, feature

#53 Feat/best form
  src/modules/forms/FormController.ts
  src/modules/forms/dtos/response/FormResponse.ts
  src/modules/forms/services/FormService.ts
  src/modules/search/SearchController.ts
  src/modules/tags/entities/Tag.ts
  src/modules/wishlists/services/WishlistItemService.ts
Labels: refactor, feature

#60 비밀번호 변경 Request 변경 요청
  src/modules/users/dto/request/UpdatePasswordRequest.ts
  src/modules/users/services/UserService.ts
Labels: fix
